name: opinion-dynamics

dependencies:
    - python == 3.7
    - pip
    - pip:
        - tensorflow==1.15
        - numpy==1.16.2
        - scikit-learn==0.21.3
        - ipykernel
        - matplotlib==3.0.3
        - mlflow==1.5.0
        - pandas==0.23.4
        - scipy==1.1.0
        - seaborn==0.9.0
        - tqdm==4.45.0
